from PyQt5 import QtCore, QtGui, QtWidgets

# Video page UI
class UiVideoPage(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(872, 634)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(100, 100, 671, 231))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(30, 60, 541, 41))
        self.lineEdit.setMinimumSize(QtCore.QSize(520, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setFrame(True)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(530, 130, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setProperty('class', 'big_button')
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 20, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton1.setGeometry(QtCore.QRect(580, 60, 61, 41))
        self.pushButton1.setObjectName("pushButton1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 190, 601, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "   Alege un videoclip ..."))
        self.pushButton.setText(_translate("Form", "Încarcă"))
        self.label.setText(_translate("Form", "Încarcă un videoclip"))
        self.pushButton1.setToolTip(_translate("Form", "<html><head/><body><p>Alege o imagine</p></body></html>"))
        self.pushButton1.setText(_translate("Form", "..."))
        self.label_2.setText(_translate("Form", "* Extensii acceptate: MP4"))